#!/usr/bin/env bash

# Find the PID of the process
pid=$(pgrep -f "4-to_infinity_and_beyond")

# Check if the process is running
if [ -z "$pid" ]; then
    echo "Process 4-to_infinity_and_beyond is not running."
else
    # Send SIGTERM signal to gracefully stop the process
    kill "$pid"
    echo "Process 4-to_infinity_and_beyond stopped."
fi
